# Generated automatically from Makefile.config.in by configure.
## Where you installed ObjectiveCaml
LIBDIR=/usr/local/lib/ocaml

## Where you want to install CamlTk libraries and binaries
INSTALLDIR=/usr/local/lib/ocaml/camltk

### What to use to compile and link with X
X11_LIBS=-ccopt " -L/opt/local/lib" -cclib " -lSM -lICE -lX11  -lm"
X_CFLAGS=-ccopt " -I/opt/local/include"

### What to use to compile and link with Tk
TCLTKINCLUDES=-ccopt "-I/usr/local/include"
TKLIBS=-ccopt "" -cclib "-ltk8.5 -ltcl8.5 -ldl "

### Making a library
RANLIB=ranlib

### Shouldn't need to change anything below

EXE=

## Tools from the Objective Caml distribution
EXCRC=$(LIBDIR)/extract_crc
EXPUNGE=$(LIBDIR)/expunge

CAMLC=ocamlc
CAMLCOMP=$(CAMLC) -c
CPP=/lib/cpp -P -Dunix
CAMLYACC=ocamlyacc -v
CAMLLEX=ocamllex
CAMLMKTOP=ocamlmktop
CAMLLIBR=$(CAMLC) -a
CAMLDEP=ocamldep
COMPFLAGS=
LINKFLAGS=

CAMLOPT=ocamlopt
CAMLOPTLIBR=$(CAMLOPT) -a

## End of configuration section
